# Generated by Django 3.0 on 2025-03-08 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('pic', models.CharField(max_length=300)),
                ('id_proof', models.CharField(max_length=300)),
                ('place', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=15)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order_main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(max_length=15)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('CUSTOMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order_sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_quntity', models.CharField(max_length=50)),
                ('ORDER_MAIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.Order_main')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=50)),
                ('pic', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=100)),
                ('CATEGORY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_quntity', models.CharField(max_length=50)),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=100)),
                ('liscense_no', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('id_proof', models.CharField(max_length=300)),
                ('place', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=10)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.Login')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=15)),
                ('rating', models.CharField(max_length=100)),
                ('review', models.CharField(max_length=100)),
                ('CUSTOMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.Customer')),
                ('SHOP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.Shop')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_date', models.DateField(max_length=15)),
                ('amnt', models.CharField(max_length=50)),
                ('status', models.CharField(default='', max_length=20)),
                ('ORDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.Order_sub')),
            ],
        ),
        migrations.AddField(
            model_name='order_sub',
            name='PRODUCT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.Product'),
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_des', models.CharField(max_length=100)),
                ('s_date', models.DateField()),
                ('e_date', models.DateField()),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=15)),
                ('notification', models.CharField(max_length=100)),
                ('SHOP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.Shop')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=15)),
                ('feedback', models.CharField(max_length=100)),
                ('CUSTOMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_boy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('pic', models.CharField(max_length=300)),
                ('id_proof', models.CharField(max_length=300)),
                ('place', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=50)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.Login')),
            ],
        ),
        migrations.CreateModel(
            name='Damaged_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=15)),
                ('about', models.CharField(max_length=300)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('CUSTOMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.Customer')),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.Product')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.Login'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=50)),
                ('date', models.DateField(max_length=15)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('reply', models.CharField(max_length=50)),
                ('CUSTOMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='SHOP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.Shop'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=15)),
                ('quantity', models.CharField(max_length=100)),
                ('CUSTOMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.Customer')),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Assign_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=50)),
                ('date', models.DateField(max_length=15)),
                ('DELIVERY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.Delivery_boy')),
                ('ORDER_SUB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.Order_sub')),
            ],
        ),
    ]
