# Generated by Django 3.0 on 2025-03-08 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=15)),
                ('reason', models.CharField(max_length=500)),
                ('ORDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.Order_main')),
            ],
        ),
    ]
