# Generated by Django 5.0.7 on 2025-03-18 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_alter_assign_order_id_alter_cart_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='liscense_no',
            new_name='location',
        ),
    ]
