# Generated by Django 5.0.7 on 2025-03-19 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_rename_liscense_no_shop_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id_proof',
        ),
    ]
