# Generated by Django 5.0.7 on 2025-03-19 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_remove_customer_id_proof'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Return',
        ),
    ]
